/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Administrator;
import domen.Kurs;
import domen.Ples;
import java.awt.Frame;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.Kontroler;
import modeli.ModelTabeleInstruktori;
import modeli.ModelTabelePlesovi;

/**
 *
 * @author Milica
 */
public class FrmDodajKurs extends javax.swing.JFrame {
    
    
    Frame frame;
    FrmGlavna glavna;
    List<Ples> listaPlesova;
    ModelTabelePlesovi mtplesovi;
    Kurs kurs;
  // Ples ples; 

    /**
     * Creates new form FrmDodajKurs
     */
    Administrator admin;
    
    public FrmDodajKurs() {
        initComponents();
    }

    public FrmDodajKurs(FrmGlavna parent, boolean modal) {
        
    }

    FrmDodajKurs(FrmGlavna parent, boolean modal, Administrator administrator) {
        super();
        initComponents();
        setLocationRelativeTo(null);
        admin = administrator;
       // srediCmbLogopedi();
       // srediCmbPacijenti();
         mtplesovi = new ModelTabelePlesovi();
       //  tabelaPlesovi.setModel(mtplesovi);
        frame = parent;
        glavna = (FrmGlavna) parent;
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        txtNazivKursa = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPlesovi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtNazivPlesa = new javax.swing.JTextField();
        btnDodajPles = new javax.swing.JButton();
        btnObrisiPles = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSifraKursa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dodavanje novog kursa");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Cena:");

        jLabel4.setText("Opis:");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        txtCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCenaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos plesa"));

        tabelaPlesovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaPlesovi);

        jLabel6.setText("Naziv plesa:");

        btnDodajPles.setText("Dodaj ples");
        btnDodajPles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPlesActionPerformed(evt);
            }
        });

        btnObrisiPles.setText("Obriši ples");
        btnObrisiPles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPlesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNazivPlesa, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDodajPles)
                .addGap(37, 37, 37)
                .addComponent(btnObrisiPles)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNazivPlesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajPles)
                    .addComponent(btnObrisiPles))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");

        jLabel1.setText("Sifra:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNazivKursa, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(txtCena, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSifraKursa))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addGap(45, 45, 45)
                .addComponent(btnOdustani)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifraKursa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivKursa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnOdustani))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 int i =1;
    private void btnDodajPlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPlesActionPerformed
         kurs.setSifraKursa(Integer.parseInt(txtSifraKursa.getText()));
        Ples noviPles = new Ples();
        noviPles.setNaziv(txtNazivPlesa.getText());
       
        
        noviPles.setSifraPlesa(vratiPlesove().size() +i);
        i++;
        if(!kurs.getListaPlesova().contains(noviPles)){
            kurs.dodajPles(noviPles);
            noviPles.setKurs(kurs);
            mtplesovi.dodajPles(noviPles);
                
            ModelTabelePlesovi mtsPlesovi =  (ModelTabelePlesovi) tabelaPlesovi.getModel();
            tabelaPlesovi.setModel(mtplesovi);// ovo je novi
            mtsPlesovi.fireTableDataChanged();
           

           
           
        }else{
            JOptionPane.showMessageDialog(this, "Већ постоји ставка са том шифром!","Грешка",JOptionPane.ERROR_MESSAGE);
        }
       
        
    }//GEN-LAST:event_btnDodajPlesActionPerformed

    private void txtCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCenaActionPerformed

    private void btnObrisiPlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPlesActionPerformed
        int red = tabelaPlesovi.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Морате изабрати ред.", "Упозорење!",JOptionPane.INFORMATION_MESSAGE);
        }else{
            Ples izabraniPles = mtplesovi.vratiIzabraniPles(red);
            mtplesovi.getListaPlesova().remove(izabraniPles);
            mtplesovi.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnObrisiPlesActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        if(ispravno()){
           
            
            int sifra = Integer.parseInt(txtSifraKursa.getText());
            
            kurs.setSifraKursa(sifra);
            kurs.setNazivKursa(txtNazivKursa.getText());
            kurs.setCena(Double.parseDouble(txtCena.getText()));
            kurs.setOpis(txtOpis.getText());
            kurs.setAdministrator(admin);
            mtplesovi.setKurs(kurs);
            ModelTabelePlesovi mtplesovi = (ModelTabelePlesovi) tabelaPlesovi.getModel();
         //   tabelaPlesovi.setModel(mtplesovi);
          //  mtplesovi = (ModelTabelePlesovi) tabelaPlesovi.getModel();
            if(mtplesovi.getKurs() == null){
                System.out.println("NULL vraca u frmDodajKurs");
                
            }
                    
            if (mtplesovi.getKurs().getListaPlesova().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate uneti bar jedan ples!","Greška!",JOptionPane.ERROR_MESSAGE);
                return;
            }
         
            
            try {
                kurs.setListaPlesova(mtplesovi.getKurs().getListaPlesova());
            if (Kontroler.getInstanca().dodajKurs(kurs)==true) {
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio novi kurs.", "Uspešno!",JOptionPane.INFORMATION_MESSAGE);
                FrmGlavna.dodajRedUTabeluK(kurs);
                this.dispose();
            }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti kurs.", "Greška!",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(FrmDodajKurs.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDodajKurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDodajKurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDodajKurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDodajKurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDodajKurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajPles;
    private javax.swing.JButton btnObrisiPles;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaPlesovi;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNazivKursa;
    private javax.swing.JTextField txtNazivPlesa;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtSifraKursa;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
       
        
        kurs = new Kurs();
        kurs.setListaPlesova(new LinkedList<>());
        ModelTabelePlesovi mtp = new ModelTabelePlesovi();
        mtp.setKurs(kurs);
        tabelaPlesovi.setModel(mtp);  
        txtSifraKursa.setEditable(false);
        kurs.setSifraKursa(vratiKurseve().size() +1);
       // txtSifraPlesa.setEnabled(false);
       //  Ples ples = new Ples();
       //  ples.setSifraPlesa(vratiPlesove().size() +1);
       // txtSifraPlesa.setText(String.valueOf(ples.getSifraPlesa()));
        txtSifraKursa.setText(String.valueOf(kurs.getSifraKursa()));
    }

    private List<Kurs> vratiKurseve() {
        List<Kurs> listaKurseva = new LinkedList<>();
        try {
            listaKurseva = Kontroler.getInstanca().vratiSveKurseve();
            
        } catch (Exception ex) {
            Logger.getLogger(FrmDodajKurs.class.getName()).log(Level.SEVERE, null, ex);
        }
        return listaKurseva;
    }

    private List<Ples> vratiPlesove() {
        List<Ples> listaPlesova = new LinkedList<>();
        try{
            listaPlesova = Kontroler.getInstanca().vratiSvePlesove();
            
        }catch(Exception ex){
           Logger.getLogger(FrmDodajKurs.class.getName()).log(Level.SEVERE, null, ex);

        }
        return listaPlesova;
    }

    private boolean ispravno() {
        if(txtSifraKursa.getText().isEmpty() || txtNazivKursa.getText().isEmpty() || txtCena.getText().isEmpty() || txtOpis.getText().isEmpty() ||
                txtNazivPlesa.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Морате унети сва поља.", "Упозорење!",JOptionPane.INFORMATION_MESSAGE);
            return false;
        }else{
        return true;
        }
    }

    
}
