/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Administrator;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logika.Kontroler;
import sesija.Sesija;

/**
 *
 * @author Milica
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    
    Administrator ulogovaniAdmin;
          
    public FrmLogin() {
        initComponents();
        setSize(430, 270);
        setLocationRelativeTo(null);
        pripremiFormu();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                    Exit();
            }
            
        
        
        });
    }
    
    void Exit(){
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da odustanete?", "Upozorenje!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (odgovor == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnOdustani = new javax.swing.JButton();
        btnPrijaviSe = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/novo novov.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/novo novov.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Prijavljivanje");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        txtPassword.setText("Lozinka");
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(160, 150, 200, 20);

        btnOdustani.setBackground(new java.awt.Color(239, 16, 40));
        btnOdustani.setForeground(new java.awt.Color(255, 255, 255));
        btnOdustani.setText("Odustani");
        btnOdustani.setBorder(new javax.swing.border.MatteBorder(null));
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });
        getContentPane().add(btnOdustani);
        btnOdustani.setBounds(265, 190, 100, 30);

        btnPrijaviSe.setBackground(new java.awt.Color(239, 16, 40));
        btnPrijaviSe.setForeground(new java.awt.Color(255, 255, 255));
        btnPrijaviSe.setText("Prijavi se");
        btnPrijaviSe.setBorder(new javax.swing.border.MatteBorder(null));
        btnPrijaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijaviSeActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrijaviSe);
        btnPrijaviSe.setBounds(160, 190, 90, 30);

        txtUsername.setText("Korisničko ime");
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(160, 110, 200, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/novo novov.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 230);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 70, 57, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da odustanete?", "Upozorenje!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (odgovor == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if(String.valueOf(txtPassword.getPassword()).equals("Lozinka")){
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(String.valueOf(txtPassword.getPassword()).equals("")){
            txtPassword.setText("Lozinka");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if(String.valueOf(txtUsername.getText()).equals("Korisničko ime")){
            txtUsername.setText("");
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if(String.valueOf(txtUsername.getText()).equals("")){
            txtUsername.setText("Korisničko ime");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void btnPrijaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijaviSeActionPerformed
        
        String username = txtUsername.getText();
        char[] pass = txtPassword.getPassword();
        String password = String.copyValueOf(pass);
        
        try {
            if((txtUsername.getText().equals("Korisničko ime"))&& (String.valueOf(txtPassword.getPassword()).equals("Lozinka"))){
            JOptionPane.showMessageDialog(this, "Korisničko ime i lozinka ne smeju biti prazne vrednosti.", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                return;
        }
            if((txtUsername.getText().equals("Korisničko ime")) && (!String.valueOf(txtPassword.getPassword()).equals("Lozinka"))){
                JOptionPane.showMessageDialog(this, "Korisničko ime i lozinka ne smeju biti prazne vrednosti.", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if((!txtUsername.getText().equals("Korisničko ime")) && (String.valueOf(txtPassword.getPassword()).equals("Lozinka"))){
                JOptionPane.showMessageDialog(this, "Korisničko ime i lozinka ne smeju biti prazne vrednosti.", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(!username.isEmpty() && !password.isEmpty()){
            ulogujSe(username, password);
            JOptionPane.showMessageDialog(this, "Administrator je uspešno ulogovan.", "Uspešno!", JOptionPane.INFORMATION_MESSAGE);
            FrmGlavna fg = new FrmGlavna(ulogovaniAdmin);
            fg.setVisible(true);
            this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Korisničko ime i lozinka ne smeju biti prazne vrednosti.", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Došlo je do greške. Unesite ponovo podatke.", "Greška!", JOptionPane.ERROR_MESSAGE);
            txtUsername.setText("Korisničko ime");
            txtPassword.setText("Lozinka");
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnPrijaviSeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        jComboBox1.setVisible(false);
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained

    }//GEN-LAST:event_jComboBox1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnPrijaviSe;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        URL slika = ClassLoader.getSystemResource("image/ples2.png");
        ImageIcon ikonica = new ImageIcon(slika);
        setIconImage(ikonica.getImage());
    }

    private void ulogujSe(String username, String password) throws Exception {
        Administrator admin = new Administrator();
        admin.setUsername(username);
        admin.setPassword(password);
        admin = Kontroler.getInstanca().nadjiAdmina(admin);
        ulogovaniAdmin = admin;
        Sesija.getInstanca().getMapa().put("admin", admin);   
    }
}
