/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Administrator;
import domen.Instruktor;
import domen.Kurs;
import domen.Polaznik;
import domen.Upis;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Konstante;
import logika.Kontroler;
import modeli.ModelTabeleKursevi;
import modeli.ModelTabeleKursevi2;
import modeli.ModelTabelePlesovi;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Milica
 */
public class FrmNoviUpis extends javax.swing.JFrame {
    
    FrmGlavna glavna;
    Administrator admin;
    ModelTabeleKursevi mtk;

    /**
     * Creates new form FrmNoviUpis
     */
    public FrmNoviUpis() {
        initComponents();
    }

    FrmNoviUpis(Administrator administrator) {
        initComponents();
        
    }

    FrmNoviUpis(FrmGlavna parent, boolean modal, Administrator administrator) {
        super();
        glavna = (FrmGlavna) parent;
        initComponents();
        setLocationRelativeTo(null);
        admin = administrator;
         // ima tamo cb isto
        lblPolaznik.setText("");
        mtk = new ModelTabeleKursevi();
        tblKursevi.setModel(mtk);
        napuniCBKursevi();
        napuniCBPolaznici();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbPolaznici = new javax.swing.JComboBox();
        cbKursevi = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lblPolaznik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKursevi = new javax.swing.JTable();
        btnObrisi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Polaznici:");

        jLabel2.setText("Kursevi:");

        cbPolaznici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPolazniciActionPerformed(evt);
            }
        });

        cbKursevi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKurseviActionPerformed(evt);
            }
        });

        lblPolaznik.setText("jLabel3");

        tblKursevi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKursevi);

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblPolaznik, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPolaznik, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnObrisi)
                .addGap(40, 40, 40))
        );

        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbPolaznici, 0, 293, Short.MAX_VALUE)
                                .addComponent(cbKursevi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbPolaznici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbKursevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPolazniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPolazniciActionPerformed
       Polaznik p = (Polaznik) cbPolaznici.getSelectedItem();
       lblPolaznik.setText(p+"");
    }//GEN-LAST:event_cbPolazniciActionPerformed

    private void cbKurseviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKurseviActionPerformed
        Kurs kurs = (Kurs) cbKursevi.getSelectedItem();

        mtk.dodajKurs(kurs); // ovde kurs nije null
    }//GEN-LAST:event_cbKurseviActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        mtk = (ModelTabeleKursevi) tblKursevi.getModel();
        int red = tblKursevi.getSelectedRow();
        if(red > -1){
        mtk.izbrisi(red);
        }else{
            JOptionPane.showMessageDialog(this, "Morate oznaciti red za brisanje", "Upozorenje!",JOptionPane.INFORMATION_MESSAGE);            
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
         if(ispravno()){
             SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd");
             Date datumUpisa = new Date();
             sdf.format(datumUpisa);
             Polaznik p = (Polaznik) cbPolaznici.getSelectedItem();
             Kurs k = (Kurs) cbKursevi.getSelectedItem();
            Upis upis = new Upis(p, k, datumUpisa, admin);
         //   List<Kurs> listaK = upis.getPolaznik().getListaKurseva();
          //  listaK.add(upis.getKurs()); // OVA DVA REDA SAM DODALA, VEROVATNO BESMISLENO ALI MORA NESTO SA TIM DA SE URADI
            if(upis != null){
                System.out.println(" UPIS NNIJE NULL");
            }
                
            try{
            if(dodajUpis(upis) == true){
            JOptionPane.showMessageDialog(this, "Систем је запамтио новог логопеда.", "Успешно!",JOptionPane.INFORMATION_MESSAGE);            this.dispose();
            
        }else{
             JOptionPane.showMessageDialog(this, "Систем није запамтио новог логопеда.", "Грешка!",JOptionPane.ERROR_MESSAGE);
        }
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti instruktora.", "Greška!",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(FrmDodajInstruktora.class.getName()).log(Level.SEVERE, null, e);
            }
        
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
 //   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNoviUpis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNoviUpis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNoviUpis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNoviUpis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNoviUpis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cbKursevi;
    private javax.swing.JComboBox cbPolaznici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPolaznik;
    private javax.swing.JTable tblKursevi;
    // End of variables declaration//GEN-END:variables

    private void napuniCBPolaznici() {
         try {
            cbPolaznici.removeAllItems();
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Konstante.VRATI_POLAZNIKE);
            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
            List<Polaznik> polaznici = (List<Polaznik>) so.getPodaci();
            
            for (Polaznik p : polaznici) {
                cbPolaznici.addItem(p);
            }
          //  cbPolaznici.setSelectedIndex(-1);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FrmDodajPolaznika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    private void napuniCBKursevi() {
        try {
            cbKursevi.removeAllItems();
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Konstante.VRATI_KURSEVE);
            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
            List<Kurs> kursevi = (List<Kurs>) so.getPodaci();
            
            for (Kurs k : kursevi) {
                cbKursevi.addItem(k);
            }
           // cbKursevi.setSelectedIndex(-1);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FrmDodajPolaznika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean ispravno() {
        return true;
    }

    private boolean dodajUpis(Upis upis) {
        
        System.out.println("USLO JE U DODAJ UPIS");
         try {
            boolean kreiran = Kontroler.getInstanca().dodajUpis(upis);
            if (kreiran == true) {
            // JOptionPane.showMessageDialog(this, "Логопед је успешно додат.", "Успешно!",JOptionPane.INFORMATION_MESSAGE);
                return true;
            }
            if(kreiran == false){
                System.out.println("KREIRAN JE FALSE ZAO MI JE");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Систем не може да запамти новог логопеда.", "Грешка!",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmNoviUpis.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    }

